package com.github.zarechenskiy.gradlehelperplugin


const val DEPENDENCY_DECLARATION_LEVEL_API = "api"
const val DEPENDENCY_DECLARATION_LEVEL_COMPILE = "compile"
const val DEPENDENCY_DECLARATION_LEVEL_IMPLEMENTATION = "implementation"
const val DEPENDENCY_DECLARATION_LEVEL_COMPILE_ONLY = "compileOnly"
const val DEPENDENCY_DECLARATION_LEVEL_COMPILE_ONLY_API = "compileOnlyApi"
const val DEPENDENCY_DECLARATION_LEVEL_RUNTIME_ONLY = "runtimeOnly"
const val DEPENDENCY_DECLARATION_LEVEL_TEST_IMPLEMENTATION = "testImplementation"
const val DEPENDENCY_DECLARATION_LEVEL_TEST_COMPILE_ONLY = "testCompileOnly"
const val DEPENDENCY_DECLARATION_LEVEL_TEST_RUNTIME_ONLY = "testRuntimeOnly"

val DEPENDENCY_DECLARATION_LEVELS = listOf(
    DEPENDENCY_DECLARATION_LEVEL_API,
    DEPENDENCY_DECLARATION_LEVEL_COMPILE,
    DEPENDENCY_DECLARATION_LEVEL_IMPLEMENTATION,
    DEPENDENCY_DECLARATION_LEVEL_COMPILE_ONLY,
    DEPENDENCY_DECLARATION_LEVEL_COMPILE_ONLY_API,
    DEPENDENCY_DECLARATION_LEVEL_RUNTIME_ONLY,
    DEPENDENCY_DECLARATION_LEVEL_TEST_IMPLEMENTATION,
    DEPENDENCY_DECLARATION_LEVEL_TEST_COMPILE_ONLY,
    DEPENDENCY_DECLARATION_LEVEL_TEST_RUNTIME_ONLY
)

const val MAIN_CHILD_MODULE_NAME = "main"
const val TEST_CHILD_MODULE_NAME = "test"

const val PROJECT_WIDE_DEPENDENCY_DECLARATION_CALL = "project"

const val INTELLIJ_MODULE_NAME_DELIMITER = '.'
const val GRADLE_MODULE_NAME_DELIMITER = ':'

const val DEPENDENCIES_BLOCK_NAME = "dependencies"

const val BUILD_GRADLE_KTS_FILE_NAME = "build.gradle.kts"

const val GRADLE_LIBRARY_NAME_PREFIX = "Gradle: "
